# Generated by Django 3.2.8 on 2021-10-29 07:34

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('อนุมัติ', 'อนุมัติ'), ('ไม่อนุมัติ', 'ไม่อนุมัติ')], max_length=10)),
                ('position', models.CharField(max_length=255)),
                ('faculty_academic', models.CharField(max_length=255)),
                ('date_request', models.DateField()),
                ('date_approval', models.DateField()),
                ('document', models.TextField()),
                ('publicity', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('image', models.ImageField(default='default.jpg', null=True, upload_to='profile_pics')),
                ('id_Position', models.CharField(max_length=20, null=True)),
                ('title_name', models.CharField(blank=True, choices=[('นาย', 'นาย'), ('นาง', 'นาง'), ('นางสาว', 'นางสาว')], max_length=10, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('personal_type', models.CharField(blank=True, choices=[('พนักงานมหาวิทยาลัย', 'พนักงานมหาวิทยาลัย'), ('ลูกจ้างชั่วคราว', 'ลูกจ้างชั่วคราว')], max_length=255, null=True)),
                ('line_of_work', models.CharField(blank=True, choices=[('วิชาการ', 'วิชาการ'), ('สนับสนุน', 'สนับสนุน')], max_length=100, null=True)),
                ('position', models.CharField(blank=True, choices=[('อาจารย์', 'อาจารย์'), ('เจ้าหน้าที่บริหารงานทั้วไป', 'เจ้าหน้าที่บริหารงานทั้วไป'), ('บุคลากร', 'บุคลากร'), ('นักวิชาการศึกษา', 'นักวิชาการศึกษา'), ('นักวิเคราะห์นโยบายและเเผน', 'นักวิเคราะห์นโยบายและเเผน'), ('นักประชาสัมพันธ์', 'นักประชาสัมพันธ์'), ('นักวิทยาศาสตร์', 'นักวิทยาศาสตร์'), ('นักวิชาการโสตทัศนศึกษา', 'นักวิชาการโสตทัศนศึกษา'), ('นักวิชาการคอมพิวเตอร์', 'นักวิชาการคอมพิวเตอร์'), ('ครู', 'ครู')], max_length=100, null=True)),
                ('academic_position', models.CharField(blank=True, choices=[('ศาสตราจารย์', 'ศาสตราจารย์'), ('รองศาสตราจารย์', 'รองศาสตราจารย์'), ('ผู้ช่วยศาสตราจารย์', 'ผู้ช่วยศาสตราจารย์'), ('เชี่ยวชาญ', 'เชี่ยวชาญ'), ('ชำนาญการพิเศษ', 'ชำนาญการพิเศษ'), ('ชำนาญการ', 'ชำนาญการ')], max_length=100, null=True)),
                ('director_position', models.CharField(blank=True, choices=[('คณบดี', 'คณบดี'), ('รองคณบดี', 'รองคณบดี'), ('ผู้ช่วยคณบดี', 'ผู้ช่วยคณบดี'), ('ประธานหลักสูตร', 'ประธานหลักสูตร'), ('หัวหน้างาน', 'หัวหน้างาน')], max_length=100, null=True)),
                ('start_work_date', models.DateField(blank=True, default=None, null=True)),
                ('placement_date', models.DateField(blank=True, default=None, null=True)),
                ('status_job', models.DateField(blank=True, default=None, null=True)),
                ('date_birth', models.DateField(blank=True, default=None, null=True)),
                ('nationality', models.CharField(max_length=100, null=True)),
                ('religion_con', models.CharField(blank=True, choices=[('พุทธ', 'พุทธ'), ('คริสต์', 'คริสต์'), ('อิสลาม', 'อิสลาม'), ('ยิว', 'ยิว'), ('ซิกข์', 'ซิกข์'), ('บาไฮ', 'บาไฮ'), ('โซโรอัสเตอร์', 'โซโรอัสเตอร์'), ('พราหมณ์-ฮินดู', 'พราหมณ์-ฮินดู'), ('เชน', 'เชน'), ('ไม่มีศาสนา', 'ไม่มีศาสนา')], max_length=100, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('email_UP', models.EmailField(max_length=255, null=True)),
                ('address', models.TextField(null=True)),
                ('degree', models.CharField(max_length=100, null=True)),
                ('faculty', models.CharField(max_length=100, null=True)),
                ('university', models.CharField(max_length=100, null=True)),
                ('province', models.CharField(max_length=40, null=True)),
                ('country', models.CharField(max_length=40, null=True)),
                ('study_date', models.DateField(blank=True, default=None, null=True)),
                ('graduate', models.DateField(blank=True, default=None, null=True)),
                ('gpa', models.FloatField(null=True)),
                ('honors', models.CharField(max_length=100, null=True)),
                ('use_choice_con', models.CharField(blank=True, choices=[('ใช้', 'ใช้'), ('ไม่ใช้', 'ไม่ใช้')], max_length=9, null=True)),
                ('degree_Master', models.CharField(max_length=100, null=True)),
                ('faculty_Master', models.CharField(max_length=100, null=True)),
                ('university_Master', models.CharField(max_length=100, null=True)),
                ('province_Master', models.CharField(max_length=40, null=True)),
                ('country_Master', models.CharField(max_length=40, null=True)),
                ('study_date_Master', models.DateField(blank=True, default=None, null=True)),
                ('graduate_Master', models.DateField(blank=True, default=None, null=True)),
                ('gpa_Master', models.FloatField(null=True)),
                ('honors_Master', models.CharField(max_length=100, null=True)),
                ('use_choice_con_Master', models.CharField(blank=True, choices=[('ใช้', 'ใช้'), ('ไม่ใช้', 'ไม่ใช้')], max_length=9, null=True)),
                ('degree_doctorate', models.CharField(max_length=100, null=True)),
                ('faculty_doctorate', models.CharField(max_length=100, null=True)),
                ('university_doctorate', models.CharField(max_length=100, null=True)),
                ('province_doctorate', models.CharField(max_length=40, null=True)),
                ('country_doctorate', models.CharField(max_length=40, null=True)),
                ('study_date_doctorate', models.DateField(blank=True, default=None, null=True)),
                ('graduate_doctorate', models.DateField(blank=True, default=None, null=True)),
                ('gpa_doctorate', models.FloatField(null=True)),
                ('honors_doctorate', models.CharField(max_length=100, null=True)),
                ('use_choice_con_doctorate', models.CharField(blank=True, choices=[('ใช้', 'ใช้'), ('ไม่ใช้', 'ไม่ใช้')], max_length=9, null=True)),
                ('Author', models.CharField(max_length=255)),
                ('faculty_doc', models.CharField(max_length=255, null=True)),
                ('date_request', models.DateField()),
                ('date_evaluate', models.DateField()),
                ('date_expire', models.DateField()),
                ('level_evaluate_tech', models.CharField(max_length=255)),
                ('level_evaluate_document', models.CharField(max_length=255)),
                ('no_evaluate', models.IntegerField()),
                ('faculty_id', models.ManyToManyField(null=True, to='account.Faculty')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
