# Generated by Django 3.2.8 on 2021-10-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Manpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, null=True)),
                ('faculty', models.CharField(max_length=255, null=True)),
                ('master', models.IntegerField(blank=True, default='-', null=True)),
                ('phd', models.IntegerField(blank=True, default='-', null=True)),
                ('exteach', models.IntegerField(blank=True, default='-', null=True)),
                ('teach', models.IntegerField(blank=True, default='-', null=True)),
                ('asst_prof', models.IntegerField(blank=True, default='-', null=True)),
                ('assoc_prof', models.IntegerField(blank=True, default='-', null=True)),
                ('work', models.IntegerField(blank=True, default='-', null=True)),
                ('leave', models.IntegerField(blank=True, default='-', null=True)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Academice_Outstand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, null=True)),
                ('rank', models.CharField(max_length=1)),
                ('type_a', models.EmailField(default='-', max_length=255, null=True)),
                ('name', models.EmailField(default='-', max_length=255, null=True)),
                ('typeps', models.CharField(choices=[('บุคลากรสายวิชาการ', 'บุคลากรสายวิชาการ'), ('บุคลากรสายบริการ', 'บุคลากรสายบริการ')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=255, null=True)),
                ('budgetyear', models.CharField(max_length=4)),
                ('initial_budget', models.IntegerField(blank=True, default='-', null=True)),
                ('total_budget', models.IntegerField(blank=True, default='-', null=True)),
                ('balance', models.IntegerField(blank=True, default='-', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, null=True)),
                ('faculty', models.CharField(max_length=255, null=True)),
                ('total', models.IntegerField()),
                ('train_people', models.IntegerField(blank=True, default='-', null=True)),
                ('train_time', models.IntegerField(blank=True, default='-', null=True)),
                ('seminar_people', models.IntegerField(blank=True, default='-', null=True)),
                ('seminar_time', models.IntegerField(blank=True, default='-', null=True)),
                ('observe_people', models.IntegerField(blank=True, default='-', null=True)),
                ('observe_time', models.IntegerField(blank=True, default='-', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Human_resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9, null=True)),
                ('file', models.FileField(default='default.pdf', upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_request', models.DateField()),
                ('date_request_evaluate', models.DateField()),
                ('date_evaluate', models.DateField()),
                ('date_begin', models.DateField()),
                ('date_full_term', models.DateField()),
                ('position_rc', models.CharField(max_length=255)),
                ('situation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, null=True)),
                ('file', models.FileField(default='default.pdf', upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Manpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('bhd', models.IntegerField(blank=True, default='-', null=True)),
                ('master', models.IntegerField(blank=True, default='-', null=True)),
                ('sf', models.IntegerField(blank=True, default='-', null=True)),
                ('specific_sf', models.IntegerField(blank=True, default='-', null=True)),
                ('prof', models.IntegerField(blank=True, default='-', null=True)),
                ('specific_prof', models.IntegerField(blank=True, default='-', null=True)),
                ('work', models.IntegerField(blank=True, default='-', null=True)),
                ('leave', models.IntegerField(blank=True, default='-', null=True)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Study_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('ปริญญาโท', 'ปริญญาโท'), ('ปริญญาเอก', 'ปริญญาเอก')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_time', models.CharField(max_length=255)),
                ('bursary', models.CharField(max_length=255)),
                ('time', models.IntegerField(null=True)),
                ('extend_time', models.IntegerField()),
                ('extend_begin', models.DateField()),
                ('extend_end', models.DateField()),
                ('work', models.DateField()),
                ('approval', models.DateField()),
                ('requesting', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Year_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9)),
            ],
        ),
    ]
