# Generated by Django 3.2.8 on 2021-10-30 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_manpower',
            old_name='bhd',
            new_name='s_bhd',
        ),
        migrations.RenameField(
            model_name='service_manpower',
            old_name='leave',
            new_name='s_leave',
        ),
        migrations.RenameField(
            model_name='service_manpower',
            old_name='master',
            new_name='s_master',
        ),
        migrations.RenameField(
            model_name='service_manpower',
            old_name='position',
            new_name='s_position',
        ),
        migrations.RenameField(
            model_name='service_manpower',
            old_name='prof',
            new_name='s_prof',
        ),
        migrations.RenameField(
            model_name='service_manpower',
            old_name='sf',
            new_name='s_sf',
        ),
        migrations.RenameField(
            model_name='service_manpower',
            old_name='specific_prof',
            new_name='s_specific_prof',
        ),
        migrations.RenameField(
            model_name='service_manpower',
            old_name='specific_sf',
            new_name='s_specific_sf',
        ),
        migrations.RenameField(
            model_name='service_manpower',
            old_name='total',
            new_name='s_total',
        ),
        migrations.RenameField(
            model_name='service_manpower',
            old_name='work',
            new_name='s_work',
        ),
    ]
