# Generated by Django 3.2.8 on 2021-10-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20211030_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academice_outstand',
            name='name',
            field=models.CharField(default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='academice_outstand',
            name='type_a',
            field=models.CharField(default='-', max_length=255, null=True),
        ),
    ]
